Release 0.9.0
myelin-ai/engine pull request #86
Opened 2019-03-19 19:51 UTC by bash

2019-03-20 19:17 UTC, janhohenheim submitted a review, later dismissed

2019-03-20 19:18 UTC, jnferner commented
It's okay, but if you have the time, it would be nice to include the reason for the removal in the changelog.

2019-03-22 06:39 UTC, jeremystucki requested changes
Could you add a new 'TBD' section to the changelog?

2019-03-22 07:44 UTC, jeremystucki submitted a review, later dismissed

2019-03-22 08:41 UTC, janhohenheim approved these changes

2019-03-22 08:44 UTC, merged